# версия docker-compose
version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: 4dragunov/tn_roof:latest
#    build: .
    restart: always
    command: gunicorn smart_roof.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    env:
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      twilio_account_sid: ${{ secrets.TWILIO_ACCOUNT_SID }}
      twilio_auth_token: ${{ secrets.TWILIO_AUTH_TOKEN }}
      NUMBER_FROM: ${{ secrets.NUMBER_FROM }}

#    env_file:
#      - ./.env
    volumes:
      - static_volume:/code/static


  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/code/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web


